name: 'issue translator'
description: 'The action for translating non-english issues content to english.'
author: 'tomsun28'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
