name: 'issues translate action'
description: 'The action for translating non-english issues content to english.'
icon: 'alert-octagon'
color: 'orange'
author: 'tomsun28'
inputs:
  BOT_GITHUB_TOKEN: 
    description: 'The issue comment bot GITHUB_TOKEN.'
  BOT_LOGIN_NAME:
    description: 'The issue comment bot github login name.'
runs:
  using: 'node12'
  main: 'dist/index.js'
