name: 'Issues and Discussion Translator'
description: 'The action for translating Non-English issues content to English.'
branding:
  icon: 'disc'
  color: 'orange'
author: 'tomsun28'
inputs:
  BOT_GITHUB_TOKEN: 
    description: 'The issue comment bot GITHUB_TOKEN.'
  BOT_LOGIN_NAME:
    description: 'The issue comment bot github login name.'
  IS_MODIFY_TITLE: 
    description: 'Is need modify issue title, true or false, default false.'
  CUSTOM_BOT_NOTE:
    description: 'Custom bot note message.'
  APPEND_TRANSLATION:
    description: 'append translation content into issue instead of create new translation issue.'
runs:
  using: 'node16'
  main: 'dist/index.js'
